### ISSUE TITLE
FIx - Indentation issue with service annotations

### ISSUE THREAD

**Issue by NEwa-05** [traefik/traefik-hub-helm-chart#77]
Description:
There is an issue with the Service annotation indentation, when adding annotation the first spaces are not chomped accordingly.

Value example :
```yaml
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true,access_logs.s3.enabled=false
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
```

Expected result:
```yaml
---
kind: Service
metadata:
  name: traefik-hub
  namespace: traefik-hub
  labels:
    app.kubernetes.io/name: traefik-hub
    app.kubernetes.io/instance: traefik-hub-traefik-hub
    helm.sh/chart: traefik-hub-3.0.0
    app.kubernetes.io/managed-by: Helm
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true,access_logs.s3.enabled=false
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
```

Actual result:
```yaml
--
kind: Service
metadata:
  name: traefik-hub
  namespace: traefik-hub
  labels:
    app.kubernetes.io/name: traefik-hub
    app.kubernetes.io/instance: traefik-hub-traefik-hub
    helm.sh/chart: traefik-hub-3.0.0
    app.kubernetes.io/managed-by: Helm
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true,access_logs.s3.enabled=false
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
```

Fix with PR [#76](https://github.com/traefik/traefik-hub-helm-chart/pull/76)
